### PR TITLE
Update flutter-app-demo.

### PR DESCRIPTION
**Pull request by dvc94ch**
Still missing the window plugin

### CODE REVIEW

**Comment by csnewman** [comment]
I have created a PR with the final changes.

However, I've noticed a bug with your msg_stream_channel, it appears to only send one messages before stopping. There should be a message posted every second.

**Comment by dvc94ch** [comment]
yeah, wasn't able to test it since it still segfaults for me on wayland

**Comment by csnewman** [comment]
Have you tried updating your icudtl.dat?

**Comment by dvc94ch** [comment]
yeah that worked. It's still pretty broken, will take some debugging. Is sending only one message before stopping the only issue for you?

**Comment by csnewman** [comment]
Yes, thats the issue for me.

Afaik that is the only remaining issue.

**Comment by csnewman** [comment]
See https://github.com/dvc94ch/flutter-app-demo/pull/1

**Pull request closed without merging**
